<?php

	if( function_exists( 'acf_add_local_field_group' ) ) :

		acf_add_local_field_group(
			array(
				'key' => 'group_6405817d1b565',
				'title' => 'Block: Card Basic',
				'fields' => array(
					array(
						'key' => 'field_645c6c2b36eaf',
						'label' => 'Background',
						'name' => '',
						'aria-label' => '',
						'type' => 'accordion',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'open' => 0,
						'multi_expand' => 0,
						'endpoint' => 0,
					),
					array(
						'key' => 'field_6405817df317f',
						'label' => 'BG Color',
						'name' => 'bg_color',
						'aria-label' => '',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'enable_opacity' => 1,
						'return_format' => 'string',
					),
					array(
						'key' => 'field_640581ccf3180',
						'label' => 'BG Asset',
						'name' => 'bg_asset',
						'aria-label' => '',
						'type' => 'file',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'library' => 'all',
						'min_size' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_64058590f3183',
						'label' => 'BG Asset Opacity',
						'name' => 'bg_asset_opacity',
						'aria-label' => '',
						'type' => 'range',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 50,
						'min' => 0,
						'max' => 100,
						'step' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_645c6bfa27f17',
						'label' => 'Container',
						'name' => '',
						'aria-label' => '',
						'type' => 'accordion',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'open' => 0,
						'multi_expand' => 0,
						'endpoint' => 0,
					),
					array(
						'key' => 'field_640582b1f3181',
						'label' => 'Corner Radius',
						'name' => 'corner_radius',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'radius' => 'Sharp',
							'radius-half' => 'Semi-round',
							'radius-full' => 'Round',
						),
						'default_value' => 'radius',
						'return_format' => 'value',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_645c6c43521b7',
						'label' => 'Padding Size',
						'name' => 'padding_size',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'size' => 'None',
							'size-half' => 'Half',
							'size-full' => 'Full',
						),
						'default_value' => 'size',
						'return_format' => 'value',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_6405a9b12589a',
						'label' => 'Layout',
						'name' => '',
						'aria-label' => '',
						'type' => 'accordion',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'open' => 0,
						'multi_expand' => 0,
						'endpoint' => 0,
					),
					array(
						'key' => 'field_6405a9ea2589b',
						'label' => 'Small (640+)',
						'name' => 'layout_sm',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'sm' => 'Full',
							'sm-half' => 'Half',
						),
						'default_value' => 'sm',
						'return_format' => 'value',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_6405aa1d2589c',
						'label' => 'Medium (960+)',
						'name' => 'layout_md',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'md' => 'Full',
							'md-half' => 'Half',
							'md-third' => 'Third',
							'md-third-x2' => 'Two-thirds',
						),
						'default_value' => 'md',
						'return_format' => 'value',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_6405aa4b2589d',
						'label' => 'Large (1280+)',
						'name' => 'layout_lg',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'lg' => 'Full',
							'lg-half' => 'Half',
							'lg-third' => 'Third',
							'lg-third-x2' => 'Two-thirds',
							'lg-quarter' => 'Quarter',
							'lg-quarter-x2' => 'Two-quarters',
							'lg-quarter-x3' => 'Three-quarters',
						),
						'default_value' => 'lg',
						'return_format' => 'value',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_6405aa852589e',
						'label' => 'X-Large (1600+)',
						'name' => 'layout_xl',
						'aria-label' => '',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'xl' => 'Full',
							'xl-half' => 'Half',
							'xl-third' => 'Third',
							'xl-third-x2' => 'Two-thirds',
							'xl-quarter' => 'Quarter',
							'xl-quarter-x2' => 'Two-quarters',
							'xl-quarter-x3' => 'Three-quarters',
						),
						'default_value' => 'xl',
						'return_format' => 'value',
						'multiple' => 0,
						'allow_null' => 0,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'block',
							'operator' => '==',
							'value' => 'acf/card-basic',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
				'show_in_rest' => 0,
			)
		);

	endif;